version: 0.2

phases:
  pre_build:
    commands:
      - echo Loggeando en Amazon ECR...
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/vault-repo
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 137787521523.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Construyendo la imagen de Vault personalizada...
      # Aquí tu Dockerfile simplemente diría "FROM hashicorp/vault:latest" y copiaría tus configs
      - docker build -t vault-repo .
      - docker tag vault-repo:latest 137787521523.dkr.ecr.us-east-1.amazonaws.com/vault-repo:latest
  post_build:
    commands:
      - echo Subiendo a ECR...
      - docker push 137787521523.dkr.ecr.us-east-1.amazonaws.com/vault-repo:latest